# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10208a00301aa6bf712ac55a1c75fc42788ea787789ad7740d456a40be5c70b918a3f3e4edf7de3c97c64d5e3db083425a3c48bda56ee9d4a14d945a8a7af639

test:
  secret_key_base: 795990538bebd1c85396fe04a5dd4fef317636ea99dc8dbb62474dc1230c24d0081baeacee0e4888aaf82dd8a11d39d5504b2471b7be3f21031949eecb7eb2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
